-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 17:41:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Login
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Login` ;

-- -----------------------------------------------------
-- Schema Login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Login` DEFAULT CHARACTER SET utf8 ;
USE `Login` ;

-- -----------------------------------------------------
-- Table `Login`.`tbl_sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Login`.`tbl_sesion` ;

CREATE TABLE IF NOT EXISTS `Login`.`tbl_sesion` (
  `idtbl_sesion` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Celular` VARCHAR(10) NOT NULL,
  `Cedula` VARCHAR(10) NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Est_user` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idtbl_sesion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Login`.`tbl_sesion`
-- -----------------------------------------------------
START TRANSACTION;
USE `Login`;
INSERT INTO `Login`.`tbl_sesion` (`idtbl_sesion`, `Nombres`, `Apellidos`, `Direccion`, `Celular`, `Cedula`, `User`, `Password`, `Est_user`) VALUES (DEFAULT, 'David', 'Garcia', 'CLL 102 A 98', '1234567891', '1233546987', 'david', '123XD', 'A');
INSERT INTO `Login`.`tbl_sesion` (`idtbl_sesion`, `Nombres`, `Apellidos`, `Direccion`, `Celular`, `Cedula`, `User`, `Password`, `Est_user`) VALUES (DEFAULT, 'Julian', 'Tobar', 'CR 1556 B 9', '4567897454', '1234657899', 'julian', '123AA', 'A');

COMMIT;

